### ISSUE TITLE
com.alibaba.fastjson.JSONException: exepct '[', but {, pos 1, json

### ISSUE THREAD

**Issue by JiaoMing** [ligboy/retrofit-converter-fastjson#2]
`com.alibaba.fastjson.JSONException: exepct '[', but {, pos 1, json : {"status":200,"msg":"\u8fd4\u56de\u6b63\u5e38","data":{"banners":[{"img":"http:\/\/api.duocairen.com\/img\/banner\/001.png","uri":"http:\/\/m.duocairen.com\/news\/20160901001"},{"img":"http:\/\/api.duocairen.com\/img\/banner\/002.png","uri":"dcb:\/\/profile"}]}}
09-04 22:55:57.983 26808-26808/cn.gogpay.dcb W/System.err:     at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:712)
09-04 22:55:57.983 26808-26808/cn.gogpay.dcb W/System.err:     at com.alibaba.fastjson.serializer.CollectionCodec.deserialze(CollectionCodec.java:189)
09-04 22:55:57.983 26808-26808/cn.gogpay.dcb W/System.err:     at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:682)
09-04 22:55:57.983 26808-26808/cn.gogpay.dcb W/System.err:     at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:655)
09-04 22:55:57.983 26808-26808/cn.gogpay.dcb W/System.err:     at com.alibaba.fastjson.JSON.parseObject(JSON.java:216)
09-04 22:55:57.983 26808-26808/cn.gogpay.dcb W/System.err:     at com.alibaba.fastjson.JSON.parseObject(JSON.java:188)
09-04 22:55:57.983 26808-26808/cn.gogpay.dcb W/System.err:     at retrofit2.converter.fastjson.FastJsonResponseBodyConverter.convert(FastJsonResponseBodyConverter.java:33)
09-04 22:55:57.983 26808-26808/cn.gogpay.dcb W/System.err:     at retrofit2.converter.fastjson.FastJsonResponseBodyConverter.convert(FastJsonResponseBodyConverter.java:12)
09-04 22:55:57.983 26808-26808/cn.gogpay.dcb W/System.err:     at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:117)
09-04 22:55:57.983 26808-26808/cn.gogpay.dcb W/System.err:     at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
09-04 22:55:57.984 26808-26808/cn.gogpay.dcb W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
09-04 22:55:57.984 26808-26808/cn.gogpay.dcb W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
09-04 22:55:57.984 26808-26808/cn.gogpay.dcb W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
09-04 22:55:57.984 26808-26808/cn.gogpay.dcb W/System.err:     at rx.Subscriber.setProducer(Subscriber.java:211)
09-04 22:55:57.984 26808-26808/cn.gogpay.dcb W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
09-04 22:55:57.984 26808-26808/cn.gogpay.dcb W/System.err:     at rx.Subscriber.setProducer(Subscriber.java:205)
09-04 22:55:57.984 26808-26808/cn.gogpay.dcb W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
09-04 22:55:57.984 26808-26808/cn.gogpay.dcb W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
09-04 22:55:57.984 26808-26808/cn.gogpay.dcb W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
09-04 22:55:57.984 26808-26808/cn.gogpay.dcb W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
09-04 22:55:57.984 26808-26808/cn.gogpay.dcb W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:8666)
09-04 22:55:57.984 26808-26808/cn.gogpay.dcb W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
09-04 22:55:57.984 26808-26808/cn.gogpay.dcb W/System.err:     at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:220)
09-04 22:55:57.984 26808-26808/cn.gogpay.dcb W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
09-04 22:55:57.984 26808-26808/cn.gogpay.dcb W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
09-04 22:55:57.984 26808-26808/cn.gogpay.dcb W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-04 22:55:57.984 26808-26808/cn.gogpay.dcb W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask`

**Comment by ligboy** [comment]
您好，通过错误栈信息推测你应该的返回类型和json实际类型不符造成。
请附上你API接口定义的代码片段
