### ISSUE TITLE
如下错误信息，求速回！

### ISSUE THREAD

**Issue by parcool** [ligboy/retrofit-converter-fastjson#3]
`09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err: com.alibaba.fastjson.JSONException: syntax error, expect {, actual pos 264, json : {"responseCode":1,"source":"Android_","object":"{\"versionCode\":2,\"log\":\"XXX\",\"url\":\"https://xxx/app-debug.apk\"}","responseMsg":"获取数据成功!","datetime":1474208151634}, fieldName object
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:384)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:97)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at com.alibaba.fastjson.parser.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:45)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at com.alibaba.fastjson.parser.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:788)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:648)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at com.alibaba.fastjson.parser.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:97)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:682)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:655)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at com.alibaba.fastjson.JSON.parseObject(JSON.java:216)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at com.alibaba.fastjson.JSON.parseObject(JSON.java:188)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at retrofit2.converter.fastjson.FastJsonResponseBodyConverter.convert(FastJsonResponseBodyConverter.java:33)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at retrofit2.converter.fastjson.FastJsonResponseBodyConverter.convert(FastJsonResponseBodyConverter.java:12)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:117)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at rx.Subscriber.setProducer(Subscriber.java:211)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at rx.Subscriber.setProducer(Subscriber.java:205)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at rx.Subscriber.setProducer(Subscriber.java:205)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:8666)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:220)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-18 22:15:51.981 7318-7318/android.test.parcool W/System.err:     at java.lang.Thread.run(Thread.java:818)`

这是完整JSON字符串：
`{"responseCode":1,"source":"Android_","object":"{\"versionCode\":2,\"log\":\"XXX\",\"url\":\"https://xxx/app-debug.apk\"}","responseMsg":"获取数据成功!","datetime":1474208151634}`

解析的实体：
`public class UpdateVersionModel {
    private String log;
    private String url;
    private int versionCode;

```
public String getLog() {
    return log;
}

public void setLog(String log) {
    this.log = log;
}

public String getUrl() {
    return url;
}

public void setUrl(String url) {
    this.url = url;
}

public int getVersionCode() {
    return versionCode;
}

public void setVersionCode(int versionCode) {
    this.versionCode = versionCode;
}
```

}`

当然，前面还有一个BaseModel：
` public class BaseResultModel<人工空格T>{
    private String source;
    private String target;
    private String action;
    private long datetime;
    private String responseCode;
    private String responseMsg;
    private T object;

```
public String getSource() {
    return source;
}

public void setSource(String source) {
    this.source = source;
}

public String getTarget() {
    return target;
}

public void setTarget(String target) {
    this.target = target;
}

public String getAction() {
    return action;
}

public void setAction(String action) {
    this.action = action;
}

public long getDatetime() {
    return datetime;
}

public void setDatetime(long datetime) {
    this.datetime = datetime;
}

public String getResponseCode() {
    return responseCode;
}

public void setResponseCode(String responseCode) {
    this.responseCode = responseCode;
}

public String getResponseMsg() {
    return responseMsg;
}

public void setResponseMsg(String responseMsg) {
    this.responseMsg = responseMsg;
}

public T getObject() {
    return object;
}

public void setObject(T object) {
    this.object = object;
}
```

}`

解析的实体格式就是BaseModel<人工空格UpdateVersionModel >。求速回~

**Comment by ligboy** [comment]
请注意核对你json中object字段的类型实际为String，而非你认为的object类型，因而解析出错。

**Comment by parcool** [comment]
@ligboy  谢谢。。。就是这么回事！
